const TRIGGER_PHRASES = [
  "show me jobs",
  "find me a job",
  "i need a job",
  "any jobs available",
  "any job available",
  "job opportunities",
  "latest jobs",
  "tech jobs",
  "software jobs",
  "dev jobs",
  "jobs in tech",
  "jobs for developers",
  "entry level jobs",
  "junior jobs",
  "senior jobs",
  "remote jobs",
  "work from home jobs",
  "wfh jobs",
  "online jobs",
  "i'm job hunting",
  "actively looking for work",
  "open to work",
  "job search",
  "help me find work",
  "need employment",
  "looking for employment",
  "any openings",
  "job openings",
  "job listings",
  "job vacancies",
  "job postings",
  "new job listings",
  "fresh jobs",
  "recent job postings",
  "apply for job",
  "i need job",
  "jobs i can apply to",
  "suitable jobs for me",
  "jobs matching my skills",
  "find jobs for me",
  "recommend jobs",
  "best jobs right now",
  "good paying jobs",
  "high paying tech jobs",
  "well paying jobs",
  "salary jobs",
  "paid jobs",
  "paying jobs",
  "jobs with good salary",
  "six figure jobs",
  "jobs that pay well",
  "find internship",
  "internship opportunities",
  "tech internship",
  "software internship",
  "dev internship",
  "coding internship",
  "paid internship",
  "free internship",
  "remote internship",
  "internship for fresh grad",
  "internship for students",
  "summer internship",
  "winter internship",
  "graduate internship",
  "undergraduate internship",
  "looking for internship",
  "need internship",
  "intern position",
  "intern role",
  "intern openings",
  "where to find internship",
  "internship listings",
  "internship posting",
  "internship applications",
  "apply for internship",
  "how to get internship",
  "internship with stipend",
  "internship with salary",
  "internship 2024",
  "internship 2025",
  "best internships",
  "top internships",
  "good internship",
  "internship in my field",
  "internship opportunities near me",
  "remote internship opportunities",
  "online internship",
  "virtual internship",
  "work experience opportunity",
  "placement opportunity",
  "industrial training",
  "it opportunity",
  "siwes opportunity",
  "attachment opportunity",

  "any hackathons",
  "upcoming hackathons",
  "hackathon this month",
  "hackathon this weekend",
  "coding challenge",
  "coding competition",
  "programming contest",
  "build competition",
  "tech competition",
  "online hackathon",
  "virtual hackathon",
  "remote hackathon",
  "hackathon with prizes",
  "hackathon cash prize",
  "hackathon prize money",
  "win hackathon",
  "hackathon for beginners",
  "hackathon for students",
  "hackathon for developers",
  "join hackathon",
  "register hackathon",
  "hackathon registration",
  "hackathon deadline",
  "hackathon ideas",
  "solo hackathon",
  "team hackathon",
  "best hackathons",
  "top hackathons",
  "global hackathon",
  "local hackathon",
  "african hackathon",
  "nigerian hackathon",
  "hackathon africa",
  "mlh hackathon",
  "devpost hackathon",
  "open source hackathon",
  "ai hackathon",
  "web3 hackathon",
  "blockchain hackathon",
  "health hackathon",
  "fintech hackathon",
  "startup hackathon",
  "social impact hackathon",
  "edu hackathon",
  "climate hackathon",
  "build to win",
  "build challenge",
  "sprint challenge",
  "24hr hackathon",
  "48hr hackathon",
  "72hr hackathon",
  "weekend hackathon",
 
  "tech fellowship",
  "software fellowship",
  "engineering fellowship",
  "fellowship opportunities",
  "fellowship programs",
  "fellowship 2024",
  "fellowship 2025",
  "paid fellowship",
  "fellowship with stipend",
  "fellowship funding",
  "fellowship application",
  "apply fellowship",
  "how to get fellowship",
  "google fellowship",
  "microsoft fellowship",
  "meta fellowship",
  "amazon fellowship",
  "twitter fellowship",
  "outreachy fellowship",
  "alx fellowship",
  "andela fellowship",
  "semicolon fellowship",
  "africa fellowship",
  "remote fellowship",
  "fellowship for africans",
  "fellowship for nigerians",
  "fellowship for students",
  "fellowship for early career",
  "fellowship for women in tech",
  "fellowship for underrepresented",
  "fellowship open application",
  "fellowship deadline",
  "fellowship cohort",
  "fellowship next cohort",
  "fellowship rolling admission",
  "open fellowship",
  "new fellowship",
  "tech grant",
  "startup grant",
  "developer grant",
  "grant funding",
  "grant opportunity",
  "small grant",
  "microgrant",
  "micro grant",
  "grant application",
  "apply for grant",
  "grant for africans",
  "grant for nigeria",
  "grant for students",
  "grant for developers",
  "grant for women",
  "grant for early stage",
  "equity free grant",
  "non dilutive grant",
  "government grant",
  "ngos grant",
  "foundation grant",
  "open source grant",
  "oss grant",
  "grant program",
  "grant program 2024",
  "grant program 2025",
  "grant money",
  "funding",
  "free funding",
  "seed funding",
  "pre seed",
  "early stage funding",
  "pitch for funding",
  "pitch competition",
  "funding competition",
  "startup competition",
  "business grant",
  "tech startup grant",
  "social enterprise grant",
  "impact grant",
  "program",
  "programs",
  "tech program",
  "accelerator",
  "accelerator program",
  "incubator",
  "incubator program",
  "bootcamp",
  "coding bootcamp",
  "free bootcamp",
  "scholarship",
  "scholarship opportunity",
  "tech scholarship",
  "alx program",
  "andela program",
  "google program",
  "microsoft program",
  "meta program",
  "amazon program",
  "apple program",
  "github program",
  "open source program",
  "gsoc",
  "google summer of code",
  "outreachy",
  "mlsa",
  "gdsc",
  "developer program",
  "beta program",
  "early access program",
  "mentorship program",
  "mentorship opportunity",
  "get mentored",
  "find a mentor",
  "tech mentor",
  "career program",
  "upskill program",
  "training program",
  "free training",
  "paid training",
  "certification program",
  "free certification",
  "online program",
  "remote program",
  "cohort",
  "next cohort",
  "cohort based program",
  "cohort deadline",
  "i need work",
  "need money",
  "broke need job",
  "fresh grad no job",
  "unemployed looking for work",
  "no job help me",
  "just graduated need job",
  "i graduated please help",
  "grad looking for work",
  "new grad job",
  "entry level no experience",
  "no experience job",
  "job without experience",
  "first job",
  "my first job",
  "looking for first job",
  "help me get job",
  "assist me find job",
  "job assistance",
  "career help",
  "career advice",
  "career guidance",
  "what job fits me",
  "what career should i do",
  "help with career",
  "career switch",
  "switching careers",
  "career change",
  "change my career",
  "tired of my job",
  "hate my job need new one",
  "want new job",
  "ready for new opportunity",
  "exploring opportunities",
  "open for opportunities",
  "i'm available",
  "available for hire",
  "hire me",
  "looking to be hired",
  "ready to work",
  "willing to work",
  "can work remotely",
  "available immediately",
  "available to start now",
  "can start asap",
  "asap job",
  "urgent job",
  "quick job",
  "fast job",
  "show me opportunities",
  "any opportunities",
  "fresh opportunities",
  "latest opportunities",
  "new opportunities",
  "best opportunities",
  "top opportunities",
  "opportunities for developers",
  "opportunities in tech",
  "tech opportunity",
  "opportunities this month",
  "this week opportunities",
  "opportunities today",
  "opportunity for me",
  "find opportunities",
  "look for opportunities",
  "search opportunities",
  "opportunity search",
  "check opportunities",
  "what's available",
  "what's out there",
  "what opportunities exist",
  "scan for opportunities",
  "pull up opportunities",
  "get opportunities",
  "load opportunities",
  "fetch me something",
  "fetch opportunities",
  "drop opportunities",
  "drop jobs",
  "drop internships",
  "send opportunities",
  "send jobs",
  "any new thing",
  "any update",
  "updates please",
  "give me update",
  "what's new",
  "what's fresh",
  "new listings",
  "new postings",
  "new openings",
  "abeg help me find job",
  "abeg i need work",
  "abeg any job dey",
  "any job dey",
  "work dey",
  "job dey",
  "e get job for me",
  "find something for me",
  "anything for me",
  "you get something",
  "sharp sharp send job",
  "send am now",
  "oya send",
  "make i see something",
  "make i see opportunities",
  "show me something",
  "drop am",
  "anything good out there",
  "how far with jobs",
  "any good gig",
  "i dey find work",
  "i dey look for work",
  "i don graduate need job",
  "fresh from school need job",
  "just finished school",
  "nysc done need job",
  "after nysc what next",
  "post nysc job",
  "corper looking for job",
  "where work dey",
  "where i go find job",
  "i need skill up",
  "help me skill up",
  "opportunity to learn",
  "learn and earn",
  "learn while working",
  "side hustle",
  "gig work",
  "freelance job",
  "contract job",
  "part time job",
  "full time job",
  "remote work",
  "work anywhere",
  "digital job",
  "online work",
  "make money online",
  "earn online",
  "passive income tech",
  "build and earn",
  "tech side hustle",
  "i want to apply",
  "ready to apply",
  "rolling application",
  "last minute application",
  "last chance opportunity",
  "closing soon",
  "almost closing",
  "closes tomorrow",
  "closes today",
  "open application",
  "currently accepting",
  "accepting applications",
  "application window",
  "application period",
  "applications open",
  "just opened",
  "newly opened",
  "new posting",
  "just posted",
  "posted today",
  "posted this week",
  "posted recently",
  "fresh listing",
  "trending opportunity",
  "hot opportunity",
  "viral opportunity",
  "popular opportunity",
  "competitive opportunity",
  "apply and win",
  "opportunity with stipend",
  "paid opportunity",
  "scholarship with allowance",
  "funded opportunity",
  "fully funded",
  "fully funded program",
  "free to apply",
  "no application fee",
  "free application",
  "software engineer job",
  "frontend job",
  "backend job",
  "fullstack job",
  "full stack job",
  "mobile developer job",
  "android job",
  "ios job",
  "react job",
  "vue job",
  "angular job",
  "node job",
  "python job",
  "django job",
  "javascript job",
  "typescript job",
  "java job",
  "kotlin job",
  "flutter job",
  "react native job",
  "devops job",
  "cloud job",
  "aws job",
  "gcp job",
  "azure job",
  "data science job",
  "machine learning job",
  "ai job",
  "artificial intelligence job",
  "data analyst job",
  "data engineer job",
  "cybersecurity job",
  "security analyst job",
  "blockchain job",
  "web3 job",
  "solidity job",
  "smart contract job",
  "ui designer job",
  "ux designer job",
  "product designer job",
  "product manager job",
  "project manager job",
  "scrum master job",
  "qa engineer job",
  "test engineer job",
  "embedded systems job",
  "firmware job",
  "systems engineer job",
  "network engineer job",
  "database admin job",
  "sql job",
  "nosql job",
  "mongodb job",
  "golang job",
  "rust job",
  "c plus plus job",
  "c sharp job",
  "dotnet job",
  "i want to grow",
  "want to level up",
  "want to upskill",
  "grow my career",
  "advance my career",
  "career advancement",
  "career development",
  "career opportunity",
  "career move",
  "strategic career",
  "next step in career",
  "what next in my career",
  "next career level",
  "senior engineer role",
  "lead engineer role",
  "engineering manager",
  "tech lead role",
  "staff engineer",
  "principal engineer",
  "director of engineering",
  "vp of engineering",
  "cto role",
  "dream job",
  "ideal job",
  "perfect job",
  "job i love",
  "passion driven job",
  "purpose driven job",
  "meaningful work",
  "impactful job",
  "make a difference tech",
  "change the world tech",
  "social impact tech",
  "nonprofit tech",
  "ngo tech job",
  "mission driven job",
  "equity job",
  "diversity hiring",
  "inclusive hiring",
  "hire for diversity",
  "women in tech job",
  "underrepresented in tech",
  "minority in tech",
  "black in tech",
  "africa in tech",
  "african developer",
  "nigerian developer job",
  "diaspora job",
  "global remote job",
  "can you find me a job",
  "please find me a job",
  "i need help finding a job",
  "help me search for jobs",
  "search jobs for me",
  "scan jobs for me",
  "do a job search",
  "run a job search",
  "pull up some jobs",
  "what jobs are there",
  "what opportunities are there",
  "show me what you got",
  "what do you have for me",
  "anything for me today",
  "anything new today",
  "any fresh opportunities today",
  "anything open right now",
  "what's open",
  "what's currently accepting",
  "currently open applications",
  "open roles",
  "open positions",
  "open vacancies",
  "currently hiring",
  "companies hiring",
  "who is hiring",
  "who's hiring now",
  "hiring in tech",
  "tech companies hiring",
  "startups hiring",
  "big tech hiring",
  "faang hiring",
  "top companies hiring",
  "google hiring",
  "meta hiring",
  "amazon hiring",
  "microsoft hiring",
  "apple hiring",
  "netflix hiring",
  "twitter hiring",
  "spotify hiring",
  "airbnb hiring",
  "stripe hiring",
  "paystack hiring",
  "flutterwave hiring",
  "andela hiring",
  "alx hiring",
  "semicolon hiring",
  "decagon hiring",
  "zuri hiring",
  'hiring'
];

export default TRIGGER_PHRASES;